In [9]:
import tensorly as tl
from tensorly.decomposition import tucker, parafac, non_negative_tucker
import torch
from tensorly import tucker_to_tensor
import numpy as np

In [12]:
in_rand = np.random.rand(512,512,3,3)
input1 = tl.tensor(in_rand)

In [13]:
core, factors = non_negative_tucker(input1, rank=[512,512,3,3], n_iter_max=40, init='svd')
# print(core)
# print(factors)

In [14]:
core_torch = np.array(core)
print(core.shape)
factors_torch = []
factors_torch.append(np.array(factors[0]))
factors_torch.append(np.array(factors[1]))
factors_torch.append(np.array(factors[2]))
factors_torch.append(np.array(factors[3]))
[f.shape for f in factors]

(512, 512, 3, 3)


[(512, 512), (512, 512), (3, 3), (3, 3)]

In [15]:
ORG_Mat = np.einsum('ijkl,mi->mjkl', core_torch, factors_torch[0])
print(ORG_Mat.shape)
ORG_Mat = np.einsum('ijkl,mj->imkl', ORG_Mat, factors_torch[1])
print(ORG_Mat.shape)
ORG_Mat = np.einsum('ijkl,mk->ijml', ORG_Mat, factors_torch[2])
print(ORG_Mat.shape)
ORG_Mat = np.einsum('ijkl,ml->ijkm', ORG_Mat, factors_torch[2])
print(ORG_Mat.shape)

(512, 512, 3, 3)
(512, 512, 3, 3)
(512, 512, 3, 3)
(512, 512, 3, 3)


In [16]:
np.max(ORG_Mat-input1)

0.5196229103022906

In [61]:
print(ORG_Mat-input1)

[[[[-0.02302098  0.18991973  0.23303164]
   [ 0.07668987  0.57978101  0.38979834]
   [ 0.43280155 -0.05478143 -0.99973958]]

  [[-0.50788683 -0.38551453  0.74058132]
   [-0.02281324  0.36680116  0.40269464]
   [-0.24298394 -0.94462081 -0.37680347]]

  [[-0.22204294  0.29351253  0.76816138]
   [-0.17589837 -0.60713794 -0.19902189]
   [-0.03412954 -0.36780365 -0.27905704]]

  ...

  [[-0.06278766  0.25579663  0.38340658]
   [-0.29718764 -0.57708224  0.09528874]
   [-0.13471359 -0.45892929 -0.14660087]]

  [[ 0.3773088  -0.05448265 -0.87802342]
   [-0.2695713  -0.12693688  0.46779091]
   [-0.1768784  -0.09463963  0.29602327]]

  [[-0.19166371 -0.17826267  0.24795102]
   [-0.21769829 -0.50644003 -0.01070836]
   [ 0.47449351  0.26185568 -0.78644052]]]


 [[[ 0.02501368 -0.36120031 -0.40212293]
   [-0.00932268  0.33260125  0.34028257]
   [-0.23851772  0.27756995  0.78887842]]

  [[ 0.37505321  0.48522825 -0.35401512]
   [ 0.33881333  0.11101335 -0.6346204 ]
   [-0.14917841 -0.27876154  0.058

In [68]:
print(tl.tucker_tensor.tucker_to_tensor(core, factors))

ValueError: Can only take n_mode_product with a vector or a matrix.Provided array of dimension 0 not in [1, 2].

In [4]:
factors = parafac(input1, rank=3)

In [5]:
[f.shape for f in factors.factors]

[(512, 3), (512, 3), (3, 3), (3, 3)]

In [6]:
ORG_CP = tl.cp_to_tensor(factors)

In [8]:
np.max(ORG_CP-input1)

0.6259422136798302

In [7]:
print(ORG_CP-input1)

[[[[ 2.87014392e-01 -1.02249431e-01  1.74029486e-01]
   [ 2.82059593e-01 -3.55684345e-01  1.46678632e-01]
   [-1.89073036e-01  2.64270055e-01 -7.54206327e-02]]

  [[-1.26664102e-01 -3.31777852e-01 -3.43439106e-01]
   [-6.46551336e-02 -4.96103551e-01  1.46873728e-01]
   [ 4.66396176e-01  4.29447876e-01 -4.81943327e-01]]

  [[ 3.92778381e-01 -4.63176899e-01 -3.61652950e-01]
   [ 2.12186220e-01  3.71508355e-01 -3.63444717e-01]
   [-1.85700693e-02 -3.61044108e-01  1.61898096e-01]]

  ...

  [[-4.19643581e-01  4.95962120e-01 -1.73686597e-01]
   [ 1.47207366e-01 -2.86528843e-01  3.91795856e-01]
   [ 1.82240813e-01  1.25605106e-02  4.09661458e-01]]

  [[-3.20149152e-01  1.18618272e-01 -4.61815405e-01]
   [ 9.94975776e-02  2.97856007e-01 -2.47858866e-01]
   [ 1.69415866e-01  4.00374592e-01  6.61886416e-02]]

  [[ 2.72863857e-01  2.54040453e-01 -4.93254979e-01]
   [-1.95633795e-01  3.39340423e-02 -3.55451688e-01]
   [-2.65881389e-01  7.01907040e-02 -1.29438009e-01]]]


 [[[ 3.14370673e-01  4.20

In [121]:
factors.weights

array([1., 1.])

In [122]:
factors.factors

[array([[ 4.95322743e+01,  5.21380629e+01],
        [ 4.44616591e-02,  6.61290658e-01],
        [ 5.07927676e+00,  1.66176699e+01],
        [ 2.06761520e+00,  3.33306990e+01],
        [ 4.06922770e+01,  9.80318316e+00],
        [ 4.14596588e+01,  1.04989973e+01],
        [ 2.95046627e+00,  7.44725239e+00],
        [ 2.61376929e+00,  1.63092749e+00],
        [ 1.97076443e-01,  1.01778290e+00],
        [ 4.41878323e-01,  5.54907199e+00],
        [ 4.21953396e-01,  5.22647717e+00],
        [ 8.79579491e+01, -4.09418299e+01]]),
 array([[ 0.15676253,  0.42321779],
        [ 0.15201175,  0.34638015],
        [ 0.05481299,  0.04970101],
        [ 0.00644458,  0.00481193],
        [ 0.15261478,  0.35649224],
        [ 0.01748585,  0.32366351],
        [ 0.00705088,  0.01503234],
        [ 0.01992493,  0.32259482],
        [ 0.32956192, -0.33046202],
        [ 0.32956192, -0.33046202],
        [ 0.77691779,  0.1773614 ],
        [ 0.32311734, -0.33527395]])]